### PR TITLE
Update MixinRenderItem.java

### PR DESCRIPTION
**Pull request by brandyyn**
Fix mixin crash with OpenAutism

### CODE REVIEW

**Comment by Roadhog360** [comment]
"openAutism"...?

**Comment by brandyyn** [comment]
> "OpenAutism"...?

Problem?

**Comment by Roadhog360** [comment]
What is it?

**Comment by brandyyn** [comment]
> What is it?

it's an abandoned mod with no downloads anywhere and the author deleted their discord, it has a broken backport of the nutrition mod that i've ripped out in my own fork for it

the reason i want to use it is because it backports the quark runes for changing the enchantment glint colour, hence creating this mixin conflict, which i fixed with this PR

furthermore it backports the "unloader" mod and the "toolbelt" mod

also adds some cool random misc items

**Comment by Roadhog360** [comment]
Sounds actually kinda neat, I wanted to also sort of backport Quark features too

**Review by jss2a98aj — APPROVED** [review]

**Pull request merged**
